### ISSUE TITLE
Feature request: flatten populated data

### ISSUE THREAD

**Issue by cortopy** [ComfortablyCoding/strapi-plugin-transformer#14]
In Strapi v4* (and already using `strapi-plugin-transformer`) when populating fields, the joined entity comes back flatten as expected :+1: 

However, they have also added a `data` field, so you get something like:

```js
{
  image: {
   data: {
      id: 1,
      //...
    }
 }
}
```

it would be great if, like with the `attributes` field, the response is flattened to:

```js
{
  image: {
      id: 1,
      //...
 }
}
```

not sure how complex this would be but just a thought

**Comment by adriaanh** [comment]
This is related to #12 , I provided a similar situation there as well. In version 1.0.1 the data was flattened, but with 1.0.3 it is not. I have checked with Strapi version 4.0.7 and 4.1.1, and the Strapi version doesn't make a difference.

**Comment by krstivojevicv** [comment]
Option to also remove data key would be great :)

**Comment by selected-pixel-jameson** [comment]
This would then match the format that you are using in the slugify plugin as well. Right now there is inconsistency between these two plugins.

**Comment by mickaeloak** [comment]
Did this quickly if it can serve anyone or if you want to use some of it @ComfortablyCoding 
https://github.com/ComfortablyCoding/strapi-plugin-transformer/pull/15

**Comment by ComfortablyCoding** [comment]
This will be in the next release
