### ISSUE TITLE
deep relations don't work

### ISSUE THREAD

**Issue by Nisthar** [ComfortablyCoding/strapi-plugin-transformer#18]
Tested with and without the plugin, deep relations don't seems to work with the plugin turned on.

like if i retrieve posts content-type with user relation, it would work

But if i try to retrieve user's relation like user.profilePic, it won't work

**Comment by ComfortablyCoding** [comment]
> Tested with and without the plugin, deep relations don't seems to work.

If it is something that does not work when the plugin is not enabled it means it is a strapi issue. This is a [known issue](https://github.com/strapi/strapi/issues/11957) with the users in users-permissions.

**Comment by Nisthar** [comment]
> > Tested with and without the plugin, deep relations don't seems to work.
> 
> If it is something that does not work when the plugin is disabled it means it is a strapi issue. Population not working is a a [known issue](https://github.com/strapi/strapi/issues/11957) with the users in users-permissions.

No, it works without the plugin. I edited my original post.

**Comment by ComfortablyCoding** [comment]
The only reproduction I could do for this is when the profile picture is null, other than that it returned all the data properly.

**Comment by ComfortablyCoding** [comment]
The empty (null,[]) relational data bug will be fixed in the next release.

If your user has a profile picture and it is not showing please provide a reproducible repo example so I can look into it further. I have not been able to reproduce that on my side.

**Comment by ComfortablyCoding** [comment]
Fixed in 2.0.1
