### ISSUE TITLE
Error relation transform

### ISSUE THREAD

**Issue by ilamarche** [ComfortablyCoding/strapi-plugin-transformer#2]
``Hello,

I have noticed that in case of multiple relation, your service algo don't work correctly.

Can you update : 
`
		const key = _.findKey(data, (p) => p && !Array.isArray(p) && p.data);
		if (key) {
			data[key] = transform(data[key].data);
		}
`

With : 
`
		_.keys(data).forEach((key) => {
			if (data[key] && !Array.isArray(data[key]) && data[key].data !== undefined) {
				data[key] = transform(data[key].data);
			}
		})
`

;)

**Comment by ComfortablyCoding** [comment]
Hello @ilamarche  ,

Thank you for pointing that out, the fix will be published in the next release.
