### ISSUE TITLE
no transformation on graphql schema

### ISSUE THREAD

**Issue by LadghemSaid** [ComfortablyCoding/strapi-plugin-transformer#23]
is it possible to have the transformation also applied to the graphql endpoint ?

**Comment by ComfortablyCoding** [comment]
Unfortunately it is not possible at the moment to apply this plugin to graphql as I have not found a reliable way to edit the generated schema. See #13 for additional context.

If you or anyone else seeing this is aware of a way to do this PRs are always welcome.
