### ISSUE TITLE
[bug] api prefix and admin clash causes admin to break

### ISSUE THREAD

**Issue by alcir-junior-caju** [ComfortablyCoding/strapi-plugin-transformer#25]
Hello, I followed the settings correctly, and everything went right.

I created the plugins.js added the settings, and sent the settings via environment variables.

External API working perfectly.

But when I went to access the Content Type, I'm getting this error message:

<img width="705" alt="image" src="https://user-images.githubusercontent.com/6674417/171649346-ac97db6d-ff3c-4a7c-8054-35889b77ed8c.png">

And it doesn't load the Content Types, and the contents I have are gone:

<img width="458" alt="image" src="https://user-images.githubusercontent.com/6674417/171649633-ff3bf89f-7012-4e6c-94d7-643982c70f71.png">

I'm using strapi 4.1.12

And my settings:

![image](https://user-images.githubusercontent.com/6674417/171650083-59d876db-4944-431f-931c-440d03094101.png)
![image](https://user-images.githubusercontent.com/6674417/171650208-070eceab-91ba-46a1-8052-a1ddba1d1dc6.png)

If I disable the settings everything goes back to normal.
And I'm uploading the strapi with:

yarn strapi develop --watch-admin

I would love to use this extension, but with this problem I can't use it, did I miss some configuration?

Thanks for the help.

**Comment by ComfortablyCoding** [comment]
Thanks for the report, I will have to look into this. It's possible that version changed something that broke the plugin.

**Comment by alcir-junior-caju** [comment]
I noticed that this only happens when the api prefix is ​​`/`

I believe that the Admin should consume the api by this prefix, and as the structure of the api has changed, it breaks the contents.

I could be wrong, but using any prefix works normally.

I will follow this problem, thanks a lot for the help.

**Comment by ComfortablyCoding** [comment]
This should be fixed in v2.0.2
