### ISSUE TITLE
Transformer not working in v4 strapi

### ISSUE THREAD

**Issue by FernandoAme** [ComfortablyCoding/strapi-plugin-transformer#31]
Hello! Thanks for the plugin!

I'm trying to use transformer in a strapi v4 app. When calling the endpoint the data is not transformed.
I followed the documentation and it still didn't work

my ./config/plugins.js
```
module.exports = ({ env }) => ({
 'transformer': {
    enabled: true,
    config: {
      prefix: '/api/',
      responseTransforms: {
        removeAttributesKey: true,
        removeDataKey: true,
      }
    }
  },
});
```
my package.json
``` "dependencies": {
    "@strapi/plugin-graphql": "^4.2.0",
    "@strapi/plugin-i18n": "4.2.0",
    "@strapi/plugin-users-permissions": "4.2.0",
    "@strapi/strapi": "4.2.0",
    "pg": "8.6.0",
    "strapi-plugin-ckeditor5": "^2.1.1-rc.1",
    "strapi-plugin-transformer": "^2.0.2"

**Comment by raphaeldas** [comment]
Same here. Updated from v4.1.8 to v4.2.3. Attributes and Data keys are back in the json response

**Comment by FernandoAme** [comment]
Thanks for the reply. I do not use cache plugin. The only plugin I use is the transformer plugin.
I soured the build cache as well. I still get the json with the data and attribute keys

**Comment by raphaeldas** [comment]
And the plugin gets recognized correctly, if you check the Plugins Page in the Admin Panel?

**Comment by FernandoAme** [comment]
My panel
![Captura de tela de 2022-07-25 12-47-26](https://user-images.githubusercontent.com/107868637/180820513-1d278184-d75d-4f6b-9268-c56614d7f6d2.png)
![Captura de tela de 2022-07-25 12-47-17](https://user-images.githubusercontent.com/107868637/180820523-b701059d-ed69-4e5f-a06a-462b93382708.png)

**Comment by ComfortablyCoding** [comment]
Hmm strange as far as I know no major changes were released that should break the plugin.

Do you have a sample repo I can look at? Did you change any api settings?

**Comment by CrisLi** [comment]
The same issue in the Strapi `4.2.3`, only default plugins installed.

**Comment by alsantos123** [comment]
Sale 4.3.0 here

**Comment by FernandoAme** [comment]
@ComfortablyCoding 
https://github.com/fernando23depaula/strapi-cms

**Comment by ComfortablyCoding** [comment]
Thanks, will have a look.

**Comment by ComfortablyCoding** [comment]
The provided example does not look to be public anymore. I just tested it myself on a fresh install of the latest v4 and the plugin is working as expected.
