### ISSUE TITLE
LHS notation does not work

### ISSUE THREAD

**Issue by deanpeterson** [ComfortablyCoding/strapi-plugin-transformer#34]
queries like populate[author] that use LHS notation do not work

**Comment by ComfortablyCoding** [comment]
Can you clarify on what you mean by does not work? The relation shows but isn't transformed? The relation does not show? etc.

If it is not showing at all I would assume this is a permission issue and the role does not have the find/findOne permission for the author relation.

**Comment by ComfortablyCoding** [comment]
Closed due to inactivity, will reopen if necessary.
