### ISSUE TITLE
Not supported in new strapi versions

### ISSUE THREAD

**Issue by bis0072** [ComfortablyCoding/strapi-plugin-transformer#47]
Not supported in new strapi versions.
Supported in Node Versions-
  "engines": {
    "node": ">=14.19.1 <=16.x.x",
    "npm": ">=6.0.0"
  },

Not Supported in Latest Versions-
 "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  },

**Comment by ComfortablyCoding** [comment]
Thanks for the report, will release a fix.

**Comment by birdzai** [comment]
+1

Should be supported in node v18 installations

**Comment by ComfortablyCoding** [comment]
Fixed in v2.1.1
