### ISSUE TITLE
Error multiple component transform

### ISSUE THREAD

**Issue by ilamarche** [ComfortablyCoding/strapi-plugin-transformer#5]
Hello,

It's me again ^^'

I noticed that in the case of using multiple components (reusable), the transformation does not apply.

I think that instead of :
```javascript
		_.forEach(data, (value, key) => {
			if (value && !Array.isArray(value) && value.data) {
				data[key] = transform(value.data);
			}
		});
```

It should be put :
```javascript
		_.forEach(data, (value, key) => {
			if (value && !Array.isArray(value) && value.data) {
				data[key] = transform(value.data);
			} else if (value && Array.isArray(value)) {
				data[key] = data[key].map((e) => transform(e))
			}
		});
```

**Comment by ComfortablyCoding** [comment]
Hello @ilamarche 

Thank you for pointing that out, it should be fixed in the next release. Additionally I have added some tests that should cover all cases so this should not happen again.. hopefully: :)

Appreciate you taking the time to file an issue!

**Comment by ilamarche** [comment]
Perfect, thx for your reactivity ;)
