### ISSUE TITLE
Feature request: wrapping POST or PUT requests' body within `data` key if not

### ISSUE THREAD

**Issue by cssmagic** [ComfortablyCoding/strapi-plugin-transformer#51]
## Background

When we send a POST or PUT request to a content API, Strapi asks us to wrap the object in a `data` key, which is also tedious like `data` keys in responses.

GOOD:

```json
{
	"data": {
		"name": "foo bar"
	}
}
```

BAD:

```json
{
	"name": "foo bar"
}
```

The "BAD" example will get an error response, like this:

```json
{
    "error": {
        "status": 400,
        "name": "ValidationError",
        "message": "Missing \"data\" payload in the request body"
    }
}
```

## Behavior

Auto wraps the body of requests within a `data` key, transforming the "BAD" example above to the "GOOD" one.

I suppose we can do this in the middleware, too.

## Config

I propose a new config key:

| Property | Description | Type | Default | Required |
| -------- | ----------- | ---- | ------- | -------- |
| requestTransforms | The transformations to enable for the API request | Object | undefined | No |
| requestTransforms.wrapWithDataKey | Wraps the request body with `data` key if needed | Boolean | false | No |

***

Love this plugin. Thank you for your excellent work!

I can compose a PR if you like this proposal. :wink:

**Comment by ComfortablyCoding** [comment]
Great proposal! The only thing i would change is the property name from `wrapWithDataKey` to `wrapBodyWithDataKey`. 

A PR would be welcome, although not sure if we can do it via middleware like we are for the response transforms.

**Comment by cssmagic** [comment]
This name `wrapBodyWithDataKey` is really more precise 👍

**Comment by cssmagic** [comment]
I'm trying to implement this feature.

**Comment by cssmagic** [comment]
I just added a draft PR, remaining 2 problems to resolve. I will describe them later in the PR.
