### ISSUE TITLE
Transform response only for given API

### ISSUE THREAD

**Issue by mighty-phoenix** [ComfortablyCoding/strapi-plugin-transformer#62]
I want to transform the resopnse for a single particular API. How can I enable the plugin on that particular API, and leave the rest of the API responses as they are now?
Quick help would be highly appreciated.
Thanks! @ComfortablyCoding @cssmagic

**Comment by ComfortablyCoding** [comment]
With the current version the only way to do so is to send the [Strapi-Transformer-Ignore header](https://github.com/ComfortablyCoding/strapi-plugin-transformer#supported-headers) on all routes that you do not want the transforms to run.

Once the next version is released you can utilize the [denyList](#63) config setting to opt out of all apis that the transformation should not run on.

**Comment by mighty-phoenix** [comment]
@ComfortablyCoding don't you think there should be a way to do it the opposite way also, i.e, mention which routes to work on? I have too many APIs being already used at many places. So I can't enable this change on my project, as it would lead to breaking changes, and sending the [Strapi-Transformer-Ignore header](https://github.com/ComfortablyCoding/strapi-plugin-transformer#supported-headers) everywhere Strapi APIs are being called is not a sane option in my case as you would imagine.
Thanks!

**Comment by ComfortablyCoding** [comment]
Agreed, I will think about this a bit more to see optimal solution for both paradigms.

**Comment by ComfortablyCoding** [comment]
Support for both deny and allow list filtering has been released in v3

**Comment by Montaser-BE** [comment]
@ComfortablyCoding  The deny list is not working.

**Comment by ComfortablyCoding** [comment]
@Montaser-BE Please open a new issue outlining
- expected behaviour
- what is currently happening
- version of strapi
- version of the plugin
- current transformer plugin settings in plugins.js 

And any other relevant debug info.
