### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'uid')

### ISSUE THREAD

**Issue by cjboco** [ComfortablyCoding/strapi-plugin-transformer#67]
After installing your plugin, I was trying to deploy on Digital Ocean, I kept getting a build failure. Saw an error and then tried starting Strapi locally and got same error: 

```
TypeError: Cannot read properties of undefined (reading 'uid')
    at Object.module.exports [as register] (/Volumes/Strapi/api/node_modules/strapi-plugin-transformer/server/register.js:26:41)
    at Object.register (/Volumes/Strapi/api/node_modules/@strapi/strapi/lib/core/domain/module/index.js:47:46)
    at Object.register (/Volumes/Strapi/api/node_modules/@strapi/strapi/lib/core/registries/modules.js:33:19)
    at async Strapi.runLifecyclesFunctions (/Volumes/Strapi/api/node_modules/@strapi/strapi/lib/Strapi.js:541:5)
    at async Strapi.register (/Volumes/Strapi/api/node_modules/@strapi/strapi/lib/Strapi.js:401:5)
    at async Strapi.load (/Volumes/Strapi/api/node_modules/@strapi/strapi/lib/Strapi.js:487:5)
    at async Strapi.start (/Volumes/Strapi/api/node_modules/@strapi/strapi/lib/Strapi.js:217:9)
```

Using Strapi v4.6.1 - Node v16.19.1 - NPM v8.6.3

[EDIT] I added a console.log at line 26 of your register.js file and it looks like UID is not available on one of my collection types:

[Edit2] It is there, sorry. I'll research a little more before posting more info.

**Comment by cjboco** [comment]
Okay, so I added `console.log(' --debug', apis[ct].contentTypes);` at line 26 of your register.js. This is right above your `const uid = apis[ct].contentTypes[ct].uid;` call.

Here's the result:
```
 --debug {
  global: {
    kind: 'singleType',
    collectionName: 'globals',
    info: {
      singularName: 'global',
      pluralName: 'globals',
      displayName: 'Global',
      description: ''
    },
    options: { draftAndPublish: true },
    pluginOptions: { i18n: [Object] },
    attributes: {
      navigation: [Object],
      footer: [Object],
      createdAt: [Object],
      updatedAt: [Object],
      publishedAt: [Object],
      createdBy: [Object],
      updatedBy: [Object]
    },
    __schema__: {
      collectionName: 'globals',
      info: [Object],
      options: [Object],
      pluginOptions: [Object],
      attributes: [Object],
      kind: 'singleType'
    },
    modelType: 'contentType',
    modelName: 'global',
    connection: 'default',
    uid: 'api::global.global',
    apiName: 'global',
    globalId: 'Global',
    actions: {},
    lifecycles: {}
  }
}
 --debug {}
```

As you can see, there is nothing in the last '--debug' call. It's an empty object, so no 'uid' exists. 

Please let me know how I can help you debug this further, as I don't understand this plugin structure that well.

**Comment by derrickmehaffy** [comment]
From the Strapi team here, could you possibly share your entire codebase?

**Comment by cjboco** [comment]
I edited line 21 from

```
if (!Object.hasOwnProperty.call(apis, ct)) {
```

to

```
if (!Object.hasOwnProperty.call(apis, ct) || !apis[ct].contentTypes.hasOwnProperty('uid')) {
```

and Strapi starts now.

**Comment by derrickmehaffy** [comment]
(generally speaking, it's not possible for a content-type to not have a UID, we build them during the register phase)

**Comment by cjboco** [comment]
> From the Strapi team here, could you possibly share your entire codebase?

It's a private repo, not 100% sure my client would be down with that, but let me see what I can do.

**Comment by derrickmehaffy** [comment]
> > From the Strapi team here, could you possibly share your entire codebase?
> 
> It's a private repo, not 100% sure my client would be down with that, but let me see what I can do.

If you need to you can add me to the repo instead, if you need to verify I work for Strapi you can email me at derrick.mehaffy@strapi.io

**Comment by cjboco** [comment]
> > > From the Strapi team here, could you possibly share your entire codebase?
> > 
> > 
> > It's a private repo, not 100% sure my client would be down with that, but let me see what I can do.
> 
> If you need to you can add me to the repo instead, if you need to verify I work for Strapi you can email me at [derrick.mehaffy@strapi.io](mailto:derrick.mehaffy@strapi.io)

You have access

**Comment by derrickmehaffy** [comment]
> > > > From the Strapi team here, could you possibly share your entire codebase?
> > > 
> > > 
> > > It's a private repo, not 100% sure my client would be down with that, but let me see what I can do.
> > 
> > 
> > If you need to you can add me to the repo instead, if you need to verify I work for Strapi you can email me at [derrick.mehaffy@strapi.io](mailto:derrick.mehaffy@strapi.io)
> 
> You have access

not seeing the inv, is this on github?

**Comment by cjboco** [comment]
I had to add a seat... please try again.

**Comment by derrickmehaffy** [comment]
Hmmm still not seeing it :thinking:

**Comment by cjboco** [comment]
> Hmmm still not seeing it 🤔

Ahhh... I had to re-invite. How about now?

**Comment by derrickmehaffy** [comment]
There we go, got it :)

**Comment by derrickmehaffy** [comment]
Your `home-page` folder in `./src/api` is empty, that's your problem, you need to delete the `home-page` folder

**Comment by derrickmehaffy** [comment]
(it's missing the schema.json file inside of the content-type folder)

**Comment by cjboco** [comment]
I never said I was a smart! :-)

**Comment by derrickmehaffy** [comment]
happens to everyone, honestly this is something we should catch and warn about.
Welcome to the Strapi ecosystem though :)

**Comment by derrickmehaffy** [comment]
Let us know if that fixes the issue though :wink:

**Comment by cjboco** [comment]
I wonder if you can throw an error on that... something like you have a empty api end-point or something. I don't think I ever would have caught that one.

Thank you!

**Comment by derrickmehaffy** [comment]
Yeah we can do it easily, it should be wrapped in a try/catch and just dump the error and still allow the app to load without that content-type

**Comment by cjboco** [comment]
Just to confirm, I removed the directory and also reverted the register.js file and it has started perfectly!

**Comment by ComfortablyCoding** [comment]
Thanks @derrickmehaffy !

**Comment by JaydeeSale** [comment]
> || !apis[ct].contentTypes.hasOwnProperty('uid')

Can we add this into the source ? seems if we have custom controllers this also breaks the compile, and since custom controllers dont have a schema.json it fails and we cant use this plugin.
