### ISSUE TITLE
Config not being set correctly 

### ISSUE THREAD

**Issue by JaydeeSale** [ComfortablyCoding/strapi-plugin-transformer#69]
Trying to use the plugin, seems strapi config is not being set correctly.

`module.exports = ({ env }) => ({
  // ..
  transformer: {
    enabled: true,
    config: {
      responseTransforms: {
        removeAttributesKey: true,
        removeDataKey: true,
      },
      requestTransforms: {
        wrapBodyWithDataKey: true,
      },
      hooks: {
        preResponseTransform: (ctx) =>
          console.log("hello from the preResponseTransform hook!"),
        postResponseTransform: (ctx) =>
          console.log("hello from the postResponseTransform hook!"),
      },
      contentTypeFilter: {
        mode: "allow",
        uids: {
          "api::article.article": true,
          "api::category.category": {
            GET: true,
          },
        },
      },
    },
  },
  // ..
});
`

above is the config/plugin.ts file, and when i get to the plugin itself seems im getting back only the hooks object causing the middleware not to register 

`{
  hooks: {
    preResponseTransform: [Function: preResponseTransform],
    postResponseTransform: [Function: postResponseTransform]
  }
} plugin.transformer`

response from the settings-service.ts

`'use strict';

const { pluginId } = require('../util/pluginId');

module.exports = ({ strapi }) => ({
	get() {
		const value = strapi.config.get(`plugin.${pluginId}`);
		console.log("WTF", value, `plugin.${pluginId}`)
		return value
	},
});`

**Comment by JaydeeSale** [comment]
addressed in PR https://github.com/ComfortablyCoding/strapi-plugin-transformer/pull/70

**Comment by ComfortablyCoding** [comment]
That is correct behaviour. The config is not being set because the file name should be `plugins.ts` not `plugin.ts`

**Comment by JaydeeSale** [comment]
Sorry was a typo in the comment, it was in a plugins.ts file. Edited the wording, but it is definitely a bug, fixed and added to PR, i have my fork loaded into my app and is now working as expected with 4.6.0 of Strapi
