### ISSUE TITLE
[bug] custom collections are not transformed

### ISSUE THREAD

**Issue by raulmartinez1855** [ComfortablyCoding/strapi-plugin-transformer#80]
Hello,

Thank you for all the work you do on this package. I just upgraded from 2.2.0 to 3.0.1, and I am noticing that my collection types with custom route files such as:

01-collection-type-example.ts
02-collection-type-example.ts

Are now not working.  

Please let me know if there is any other information I can provide!

**Comment by ComfortablyCoding** [comment]
Could be a regression due to #74.

Can you provide a sample of what the code in those files and their corresponding routes files look like?

**Comment by ComfortablyCoding** [comment]
Sorry, been sick for the last week or so. This should be fied by #82 , still needs a bit of testing but plan to merge it over the weekend. Thanks for the code sample!

**Comment by ComfortablyCoding** [comment]
This should now be fixed in v3.1.0
