### ISSUE TITLE
Is anyway to removeAttributesKey when i use strapi-plugin-menus

### ISSUE THREAD

**Issue by mingyuyuyu** [ComfortablyCoding/strapi-plugin-transformer#89]
to reqeust api for 'http://localhost:1337/api/menus?nested&populate=*' when i use strapi-plugin-menus，it still perseve attribute key，how to resolve it，help me。
![image](https://github.com/ComfortablyCoding/strapi-plugin-transformer/assets/32156701/da94f531-2f3f-48c0-822f-68c96830f29c)

**Comment by ComfortablyCoding** [comment]
By default APIs provided by plugins are not transformed. To opt-in to transform the API endpoints for this plugin you use the plugins property in the settings. 

e.g.
```js
module.exports = ({ env }) => ({
  // ..
 'transformer': {
    enabled: true,
    config: {
      responseTransforms: {
        removeAttributesKey: true,
        removeDataKey: true,
      },
      plugins: {
        ids: {
          'menus': true,
        }
      }
    }
  },
  // ..
});
```
